---
- name: Check if Kustomize is installed
  stat:
    path: /usr/local/bin/kustomize
  register: kustomize_stat

- name: Download and install Kustomize
  shell: "curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash"
  args:
    executable: /bin/bash
  when: not kustomize_stat.stat.exists
  changed_when: true

- name: Move kustomize to /usr/local/bin if not present
  command: mv kustomize /usr/local/bin/
  become: true
  when: not kustomize_stat.stat.exists
  changed_when: true
