---
- name: Check if Kustomize is installed
  ansible.builtin.stat:
    path: /usr/local/bin/kustomize
  register: kustomize_stat

- name: Install Kustomize
  block:
    - name: Create temporary install directory
      ansible.builtin.tempfile:
        state: directory
        prefix: kustomize_install_
        path: "{{ ansible_env.HOME }}"
      register: kustomize_tmpdir

    - name: Download Kustomize install script
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
        dest: "{{ kustomize_tmpdir.path }}/install_kustomize.sh"
        mode: '0755'

    - name: Run Kustomize install script
      ansible.builtin.shell: "bash {{ kustomize_tmpdir.path }}/install_kustomize.sh"
      args:
        executable: /bin/bash
        chdir: "{{ kustomize_tmpdir.path }}"

    - name: Move kustomize to /usr/local/bin
      ansible.builtin.command: "mv {{ kustomize_tmpdir.path }}/kustomize /usr/local/bin/"
      become: true

    - name: Clean up temporary install directory
      ansible.builtin.file:
        path: "{{ kustomize_tmpdir.path }}"
        state: absent
  when: not kustomize_stat.stat.exists
