namespace: somaz94
name: ansible_k8s_iac_tool
version: 1.3.0
readme: README.md
authors:
  - somaz <noreply@example.com>
description: Collection of Ansible roles for Kubernetes tooling setup and etc..
license_file: LICENSE
tags:
  - tools
  - infrastructure
  - kubernetes
  - helm
  - krew
  - kubectl
  - kustomize
  - packer
  - pulumi
  - terraform
  - vagrant
  - shell
  - bash
  - zsh
  - fish
dependencies: {}
repository: https://github.com/somaz94/ansible-k8s-iac-tool
