---
- name: Check if kubectl is installed
  ansible.builtin.stat:
    path: /usr/local/bin/kubectl
  register: kubectl_stat

- name: Set kubectl_installed fact
  ansible.builtin.set_fact:
    kubectl_installed: "{{ kubectl_stat.stat.exists }}"

- name: Add required tools (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - gnupg
      - software-properties-common
      - wget
      - curl
      - git
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'
  become: true

- name: Retrieve the latest kubectl version
  ansible.builtin.command:
    cmd: "curl -L -s https://dl.k8s.io/release/stable.txt"
  register: latest_kubectl_version
  changed_when: false

- name: Install kubectl using binary
  block:
    - name: Download kubectl checksum
      ansible.builtin.command:
        cmd: "curl -L -s https://dl.k8s.io/release/{{ latest_kubectl_version.stdout }}/bin/linux/amd64/kubectl.sha256"
      register: kubectl_checksum
      changed_when: false

    - name: Download kubectl binary
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ latest_kubectl_version.stdout }}/bin/linux/amd64/kubectl"
        dest: "/tmp/kubectl"
        mode: '0755'
        checksum: "sha256:{{ kubectl_checksum.stdout }}"
        force: false

    - name: Install kubectl
      ansible.builtin.copy:
        src: "/tmp/kubectl"
        dest: "/usr/local/bin/kubectl"
        owner: root
        group: root
        mode: '0755'
        remote_src: true
      become: true

    - name: Clean up the downloaded binary
      ansible.builtin.file:
        path: "/tmp/kubectl"
        state: absent
  when: not kubectl_installed
