---
- name: Check if Helm is installed
  ansible.builtin.stat:
    path: /usr/local/bin/helm
  register: helm_stat

- name: Install Helm
  block:
    - name: Download Helm install script
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
        dest: "/tmp/get-helm-3.sh"
        mode: '0755'

    - name: Run Helm install script
      ansible.builtin.shell: "bash /tmp/get-helm-3.sh"
      args:
        executable: /bin/bash
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

    - name: Clean up install script
      ansible.builtin.file:
        path: "/tmp/get-helm-3.sh"
        state: absent
  when: not helm_stat.stat.exists
