---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Include group_vars
      include_vars: ../../group_vars/all/vars.yml

    - name: Add user somaz
      user:
        name: "{{ home_user }}"
        shell: /bin/bash
        createhome: true

    - name: Update apt cache.
      apt: 
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Update yum cache.
      yum:
        update_cache: true
      when: ansible_os_family == 'RedHat'

  roles:
    - role: setup_shell
    - role: install_kubectl
    - role: install_krew
    - role: install_krew_plugins
    - role: install_terraform
    - role: install_packer
    - role: install_vagrant
    - role: install_helm
    - role: install_pulumi
    - role: install_kustomize

  post_tasks:
    - name: Notify about shell config reload
      debug:
        msg: "Shell configuration will be applied on the next session."
      changed_when: false

    - name: Set ownership for .krew directory
      file:
        path: "~{{ home_user }}/.krew"
        owner: "{{ home_user }}"
        group: "{{ home_user }}"
        recurse: true
        state: directory