---
- name: Append configurations to .bashrc for specific user
  ansible.builtin.blockinfile:
    path: "{{ user_home_dir }}/.bashrc"
    create: true
    owner: "{{ home_user }}"
    mode: '0644'
    block: |
      # kubectl configurations
      source <(kubectl completion bash)
      alias k=kubectl
      complete -F __start_kubectl k

      # kubectl krew configurations
      if [ -d "${KREW_ROOT:-$HOME/.krew}/bin" ]; then
        export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
      fi

      # Additional bashrc configurations for installed packages
      complete -C /usr/bin/terraform terraform
      complete -C /usr/bin/packer packer

      # pulumi configurations
      if [ -d "$HOME/.pulumi/bin" ]; then
        export PATH="$PATH:$HOME/.pulumi/bin"
      fi
  become: true
  notify:
    - Reload shell
