---
- name: Install fish if not present
  ansible.builtin.package:
    name: fish
    state: present
  become: true

- name: Ensure fish config directory exists
  ansible.builtin.file:
    path: "{{ user_home_dir }}/.config/fish/conf.d"
    state: directory
    owner: "{{ home_user }}"
    group: "{{ home_user }}"
    mode: '0755'
    recurse: true
  become: true

- name: Configure fish shell for specific user
  ansible.builtin.blockinfile:
    path: "{{ user_home_dir }}/.config/fish/conf.d/k8s-iac-tools.fish"
    create: true
    owner: "{{ home_user }}"
    group: "{{ home_user }}"
    mode: '0644'
    block: |
      # kubectl configurations
      if type -q kubectl
        kubectl completion fish | source
        abbr -a k kubectl
      end

      # kubectl krew configurations
      if test -d $HOME/.krew/bin
        set -gx PATH $HOME/.krew/bin $PATH
      end

      # pulumi configurations
      if test -d $HOME/.pulumi/bin
        set -gx PATH $PATH $HOME/.pulumi/bin
      end
  become: true
  notify:
    - Reload shell
