---
- name: Get home directory of specific user
  ansible.builtin.getent:
    database: passwd
    key: "{{ home_user }}"

- name: Set user home directory fact
  ansible.builtin.set_fact:
    user_home: "{{ ansible_facts.getent_passwd[home_user][4] }}"

- name: Configure bash shell
  include_tasks: bash.yml
  when: "'bash' in user_shells"

- name: Configure zsh shell
  include_tasks: zsh.yml
  when: "'zsh' in user_shells"

- name: Configure fish shell
  include_tasks: fish.yml
  when: "'fish' in user_shells"
