---
- name: Install zsh if not present
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: Append configurations to .zshrc for specific user
  ansible.builtin.blockinfile:
    path: "{{ user_home_dir }}/.zshrc"
    create: true
    owner: "{{ home_user }}"
    mode: '0644'
    block: |
      # kubectl configurations
      [[ $commands[kubectl] ]] && source <(kubectl completion zsh)
      alias k=kubectl
      [[ $commands[kubectl] ]] && compdef k=kubectl

      # kubectl krew configurations
      if [ -d "${KREW_ROOT:-$HOME/.krew}/bin" ]; then
        export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
      fi

      # terraform/packer completions
      autoload -U +X bashcompinit && bashcompinit
      [[ -f /usr/bin/terraform ]] && complete -C /usr/bin/terraform terraform
      [[ -f /usr/bin/packer ]] && complete -C /usr/bin/packer packer

      # pulumi configurations
      if [ -d "$HOME/.pulumi/bin" ]; then
        export PATH="$PATH:$HOME/.pulumi/bin"
      fi
  become: true
  notify:
    - Reload shell
