---
- name: Get home directory of specific user
  shell: "eval echo ~{{ home_user }}"
  register: user_home
  changed_when: false

- name: Append configurations to .bashrc for specific user
  blockinfile:
    path: "{{ user_home.stdout }}/.bashrc"
    block: |
      # kubectl configurations
      source <(kubectl completion bash)
      alias k=kubectl
      complete -F __start_kubectl k
      
      # kubectl krew configurations
      if [ -d "${KREW_ROOT:-$HOME/.krew}/bin" ]; then
        export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
      fi

      # Additional bashrc configurations for installed packages
      complete -C /usr/bin/terraform terraform
      complete -C /usr/bin/packer packer

      # pulumi configurations
      if [ -d "$HOME/.pulumi/bin" ]; then
        export PATH="$PATH:$HOME/.pulumi/bin"
      fi
  become: no
  notify:
    - reload bashrc