---
- name: Check if Terraform is installed
  command: which terraform
  register: terraform_check
  failed_when: false
  changed_when: false

- name: Install yum-utils for RHEL/CentOS
  yum:
    name: yum-utils 
    state: present
  become: yes
  when: ansible_os_family == 'RedHat' and terraform_check.rc != 0

- name: Install Terraform for Debian/Ubuntu
  block:  
    - name: Add HashiCorp GPG key (Debian/Ubuntu)
      shell: "wget -O- https://apt.releases.hashicorp.com/gpg | \ gpg --dearmor | \ sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg"

    - name: Add HashiCorp repository (Debian/Ubuntu)
      shell: "echo \"deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main\" | sudo tee /etc/apt/sources.list.d/hashicorp.list"

    - name: Update apt and install Terraform (Debian/Ubuntu)
      apt:
        name: terraform
        update_cache: yes
  when: ansible_os_family == 'Debian' and terraform_check.rc != 0

- name: Install Terraform for RHEL/CentOS
  block:
    - name: Setup HashiCorp repo for Terraform (RHEL/CentOS)
      shell: "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
    - name: Install Terraform (RHEL/CentOS)
      yum:
        name: terraform
        state: present
  when: ansible_os_family == 'RedHat' and terraform_check.rc != 0
