---
- name: Check if Terraform is installed
  ansible.builtin.command: which terraform
  register: terraform_check
  failed_when: false
  changed_when: false

- name: Configure HashiCorp repository
  ansible.builtin.include_role:
    name: hashicorp_repo
  when: terraform_check.rc != 0

- name: Install Terraform (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ 'terraform=' + terraform_version if terraform_version | length > 0 else 'terraform' }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
  when:
    - ansible_os_family == 'Debian'
    - terraform_check.rc != 0

- name: Install Terraform (RHEL/CentOS)
  ansible.builtin.dnf:
    name: "{{ 'terraform-' + terraform_version if terraform_version | length > 0 else 'terraform' }}"
    state: present
  become: true
  when:
    - ansible_os_family == 'RedHat'
    - terraform_check.rc != 0
