---
- name: Check if Packer is installed Debian/Ubuntu
  command: packer version
  register: packer_check_debian
  failed_when: false
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: Check if Packer is installed RHEL/CentOS
  command: /usr/bin/packer version
  register: packer_check_rhel
  failed_when: false
  changed_when: false
  when: ansible_os_family == 'RedHat'

- name: Install yum-utils RHEL/CentOS
  yum:
    name: yum-utils 
    state: present
  become: yes
  when: ansible_os_family == 'RedHat' and packer_check_rhel.rc != 0

- name: Install Packer for Debian/Ubuntu
  block:
    - name: Add HashiCorp GPG key (Debian/Ubuntu)
      shell: "wget -O- https://apt.releases.hashicorp.com/gpg | \ gpg --dearmor | \ sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg"

    - name: Add HashiCorp repository (Debian/Ubuntu)
      shell: "echo \"deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main\" | sudo tee /etc/apt/sources.list.d/hashicorp.list"
      
    - name: Update apt and install Packer for (Debian/Ubuntu)
      apt:
        name: packer
        update_cache: yes
  when: ansible_os_family == 'Debian' and packer_check_debian.rc != 0

- name: Install Packer for RHEL/CentOS
  block:
    - name: Setup HashiCorp repo for Packer (RHEL/CentOS)
      shell: "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
    - name: Install Packer (RHEL/CentOS)
      yum:
        name: packer
        state: present
  when: ansible_os_family == 'RedHat' and packer_check_rhel.rc != 0

- name: Check location of packer
  command: which packer
  register: packer_location
  changed_when: false
  when: ansible_os_family == 'RedHat'

- name: Debug packer location
  debug:
    var: packer_location.stdout
  when: ansible_os_family == 'RedHat'

- name: Remove packer from /sbin
  file:
    path: /sbin/packer
    state: absent
  become: yes
  when: 
    - ansible_os_family == 'RedHat'
    - packer_location.stdout == "/sbin/packer"

- name: Create symbolic link for packer in /sbin/
  command: ln -s /usr/bin/packer /sbin/packer
  become: yes
  when: 
    - ansible_os_family == 'RedHat'
    - packer_location.stdout == "/sbin/packer"
